name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        dependency-graph: generate-and-upload
    - name: Run build with Gradle Wrapper
      run: chmod +x ./gradlew && ./gradlew build
